name: Deploy .NET 4.7.2 Console App to Azure (OIDC)

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

permissions:
  contents: read
  id-token: write

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # 1) Check that required secrets exist
  check-secrets:
    runs-on: css-windows-runner1
    outputs:
      secrets-valid: ${{ steps.secrets-valid.outputs.isvalid }}
    steps:
      - uses: actions/checkout@v3

      - id: secrets-valid
        env:
          AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          if (-not $env:AZURE_WEBAPP_NAME -or -not $env:AZURE_SUBSCRIPTION_ID) {
            "isvalid=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else {
            "isvalid=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }
        shell: pwsh

  # 2) Build and package the .NET 4.7.2 app
  build:
    runs-on: css-windows-runner1
    needs: check-secrets
    if: needs.check-secrets.outputs.secrets-valid == 'true'
    steps:
      - uses: actions/checkout@v3

      # Set up MSBuild and NuGet
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      # Restore NuGet packages for the solution
      - name: Restore dependencies
        run: nuget restore SoftwareArchitectureConsoleAppNet_4_7_2.sln

      # Build the solution using MSBuild (outputs will be in each project’s default folder)
      - name: Build solution
        run: msbuild SoftwareArchitectureConsoleAppNet_4_7_2.sln /p:Configuration=Release

      # Create a publish folder by searching for a Release folder with an executable.
      - name: Create publish folder and copy output
        run: |
          New-Item -ItemType Directory -Path publish -Force
          # Search recursively for an *.exe in a Release folder.
          $exePath = Get-ChildItem -Path . -Recurse -Filter "*.exe" | Where-Object { $_.FullName -match "Release" } | Select-Object -First 1
          if ($null -eq $exePath) {
            Write-Error "Could not find any executable in a Release folder."
            exit 1
          } else {
            $outputFolder = Split-Path $exePath.FullName -Parent
            Write-Host "Found output folder: $outputFolder"
            Copy-Item -Path "$outputFolder\*" -Destination publish -Recurse -Force
          }
        shell: pwsh

      # (Optional) List publish folder contents for debugging
      - name: List publish folder contents
        run: dir .\publish
        shell: pwsh

      # Archive (zip) the published output
      - name: Archive published output
        run: Compress-Archive -Path publish\* -DestinationPath app.zip -Force
        shell: pwsh

      # Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: app.zip

  # 3) Deploy to Azure Web App
  deploy:
    runs-on: css-windows-runner1
    needs: [build, check-secrets]
    if: needs.check-secrets.outputs.secrets-valid == 'true'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      # OIDC-based Azure login
      - name: Azure Login (OIDC)
        uses: azure/login@v1.5.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: app.zip

      # Simple health check
      - name: Validate deployment
        run: |
          sleep 10
          curl -f https://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net || exit 1
